import "./globals.css";

export const metadata = {
  title: "Sofrendo",
  description: "Generated by create next app",
};

import { Lato } from "next/font/google";

const lato = Lato({
  variable: "--font-lato",
  weight: ["100", "400", "900"],
  fallback: ["sans-serif"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className={`${lato.variable}`}>
      <body>{children}</body>
    </html>
  );
}
